/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminAccessRouteImport } from './routes/admin-access'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndustrialSupplyRouteImport } from './routes/services.industrial-supply'
import { Route as ServicesHvacRouteImport } from './routes/services.hvac'
import { Route as ServicesAgricultureRouteImport } from './routes/services.agriculture'
import { Route as ProductsCategoriesRouteImport } from './routes/products.categories'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/admin-access',
  path: '/admin-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndustrialSupplyRoute =
  ServicesIndustrialSupplyRouteImport.update({
    id: '/industrial-supply',
    path: '/industrial-supply',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesHvacRoute = ServicesHvacRouteImport.update({
  id: '/hvac',
  path: '/hvac',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAgricultureRoute = ServicesAgricultureRouteImport.update({
  id: '/agriculture',
  path: '/agriculture',
  getParentRoute: () => ServicesRoute,
} as any)
const ProductsCategoriesRoute = ProductsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-access': typeof AdminAccessRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/categories': typeof ProductsCategoriesRoute
  '/services/agriculture': typeof ServicesAgricultureRoute
  '/services/hvac': typeof ServicesHvacRoute
  '/services/industrial-supply': typeof ServicesIndustrialSupplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-access': typeof AdminAccessRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/categories': typeof ProductsCategoriesRoute
  '/services/agriculture': typeof ServicesAgricultureRoute
  '/services/hvac': typeof ServicesHvacRoute
  '/services/industrial-supply': typeof ServicesIndustrialSupplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-access': typeof AdminAccessRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/categories': typeof ProductsCategoriesRoute
  '/services/agriculture': typeof ServicesAgricultureRoute
  '/services/hvac': typeof ServicesHvacRoute
  '/services/industrial-supply': typeof ServicesIndustrialSupplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-access'
    | '/blog'
    | '/contact'
    | '/products'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/admin'
    | '/products/$slug'
    | '/products/categories'
    | '/services/agriculture'
    | '/services/hvac'
    | '/services/industrial-supply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-access'
    | '/blog'
    | '/contact'
    | '/products'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/admin'
    | '/products/$slug'
    | '/products/categories'
    | '/services/agriculture'
    | '/services/hvac'
    | '/services/industrial-supply'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin-access'
    | '/blog'
    | '/contact'
    | '/products'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/products/$slug'
    | '/products/categories'
    | '/services/agriculture'
    | '/services/hvac'
    | '/services/industrial-supply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminAccessRoute: typeof AdminAccessRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-access': {
      id: '/admin-access'
      path: '/admin-access'
      fullPath: '/admin-access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/industrial-supply': {
      id: '/services/industrial-supply'
      path: '/industrial-supply'
      fullPath: '/services/industrial-supply'
      preLoaderRoute: typeof ServicesIndustrialSupplyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/hvac': {
      id: '/services/hvac'
      path: '/hvac'
      fullPath: '/services/hvac'
      preLoaderRoute: typeof ServicesHvacRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/agriculture': {
      id: '/services/agriculture'
      path: '/agriculture'
      fullPath: '/services/agriculture'
      preLoaderRoute: typeof ServicesAgricultureRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/products/categories': {
      id: '/products/categories'
      path: '/categories'
      fullPath: '/products/categories'
      preLoaderRoute: typeof ProductsCategoriesRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsCategoriesRoute: typeof ProductsCategoriesRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsCategoriesRoute: ProductsCategoriesRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesAgricultureRoute: typeof ServicesAgricultureRoute
  ServicesHvacRoute: typeof ServicesHvacRoute
  ServicesIndustrialSupplyRoute: typeof ServicesIndustrialSupplyRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAgricultureRoute: ServicesAgricultureRoute,
  ServicesHvacRoute: ServicesHvacRoute,
  ServicesIndustrialSupplyRoute: ServicesIndustrialSupplyRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminAccessRoute: AdminAccessRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRouteWithChildren,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
